name: Lint code & compile test


on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: ict-neskar/workflows/.github/workflows/code-consistency-check.yaml@main
    secrets: inherit
    
